---
- name: Unpack files on localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove container from known_hosts
      shell: ssh-keygen -R {{ hostvars[item].ansible_host }}
      with_items: "{{ groups['containers'] }}"
    - name: Create ubuntu20 container
      shell: lxc-create -n ubuntu20 -t ubuntu -- --release focal --arch amd64 --packages openssh-server
 
    - name: Copy container config to /var/lib/lxc/ubuntu20
      shell: cp ../configs/ubuntu1/config1 /var/lib/lxc/ubuntu20/config && cp ../configs/ubuntu1/10-lxc.yaml /var/lib/lxc/ubuntu20/rootfs/etc/netplan/10-lxc.yaml
    
    - name: Create ubuntu20_1 container
      shell: lxc-create -n ubuntu20_1 -t ubuntu -- --release focal --arch amd64 --packages openssh-server
 
    - name: Copy container config to /var/lib/lxc/ubuntu20_1
      shell: cp ../configs/ubuntu2/config2 /var/lib/lxc/ubuntu20_1/config && cp ../configs/ubuntu2/10-lxc.yaml /var/lib/lxc/ubuntu20_1/rootfs/etc/netplan/10-lxc.yaml

    - name: Create ubuntu20_2 container
      shell: lxc-create -n ubuntu20_2 -t ubuntu -- --release focal --arch amd64 --packages openssh-server
 
    - name: Copy container config to /var/lib/lxc/ubuntu20_2
      shell: cp ../configs/ubuntu3/config3 /var/lib/lxc/ubuntu20_2/config && cp ../configs/ubuntu3/10-lxc.yaml /var/lib/lxc/ubuntu20_2/rootfs/etc/netplan/10-lxc.yaml

    - name: Turn on containers
      shell: lxc-start ubuntu20 && lxc-start ubuntu20_1 && lxc-start ubuntu20_2
    
    - name: Configure user in ubuntu20
      shell: lxc-attach -n ubuntu20 -- bash -c 'useradd -m -s /bin/bash szymon && echo "szymon:test" | chpasswd'

    - name: Add user to sudoers in ubuntu20
      shell: lxc-attach -n ubuntu20 -- usermod -aG sudo szymon

    - name: Configure user in ubuntu20_1
      shell: lxc-attach -n ubuntu20_1 -- bash -c 'useradd -m -s /bin/bash szymon && echo "szymon:test" | chpasswd'

    - name: Add user to sudoers in ubuntu20_1
      shell: lxc-attach -n ubuntu20_1 -- usermod -aG sudo szymon

    - name: Configure user in ubuntu20_2
      shell: lxc-attach -n ubuntu20_2 -- bash -c 'useradd -m -s /bin/bash szymon && echo "szymon:test" | chpasswd'

    - name: Add user to sudoers in ubuntu20_2
      shell: lxc-attach -n ubuntu20_2 -- usermod -aG sudo szymon

