---
- hosts: ubuntu3
  vars:
    ansible_password: "{{ password }}"
    ansible_sudo_pass: "{{ password }}"
  gather_facts: false
  become: true
  tasks:
    - name: Ensure that .ssh directory exists
      shell: lxc-stop ubuntu20_2 || echo > /dev/null
      delegate_to: localhost
    
    - name: Ensure that .ssh directory exists
      shell: lxc-destroy ubuntu20_2 || echo > /dev/null
      delegate_to: localhost

    - name: Remove container from known_hosts
      shell: ssh-keygen -R {{ ansible_host }}
      delegate_to: localhost
    
    - name: Create ubuntu20_2 container
      shell: lxc-create -n ubuntu20_2 -t ubuntu -- --release focal --arch amd64 --packages openssh-server
      delegate_to: localhost
    
    - name: Copy container config
      shell: cp ../configs/ubuntu3/config /var/lib/lxc/ubuntu20_2/config && cp ../configs/ubuntu3/10-lxc.yaml /var/lib/lxc/ubuntu20_2/rootfs/etc/netplan/10-lxc.yaml
      delegate_to: localhost

    - name: Start container
      shell: lxc-start ubuntu20_2
      delegate_to: localhost
   
    - name: Configure user {{ ansible_user }}
      shell: lxc-attach -n ubuntu20_2 -- bash -c 'useradd -m -s /bin/bash {{ ansible_user }} && echo "{{ ansible_user }}:{{ ansible_password }}" | chpasswd'
      delegate_to: localhost

    - name: Add user to sudoers
      shell: lxc-attach -n ubuntu20_2 -- usermod -aG sudo {{ ansible_user }}
      delegate_to: localhost

    - name: Install net-tools
      apt:
        name: net-tools
        state: present
